# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hello. I'm Sai Saketh Cherukuri."
email: 'ssaketh.2002@gmail.com'
description: "I'm currently a student at SSSIHL pursuing my M.Sc. in Mathematics with specialization in Computer Science."
baseurl: "https://ssaketh-ch.github.io/Saketh.portfolio.io/" # the subpath of your site, e.g. /blog
url: "https://ssaketh-ch.github.io" # the base hostname & protocol for your site, e.g. https://example.com
linkedin_username: 'Sai Saketh Cherukuri'
github_username: 'ssaketh-ch'
resume_url: 'https://your-resume-link.com'  # Update with your actual resume URL
footer_text: '© 2024 Sai Saketh Cherukuri | <a href="https://www.linkedin.com/in/sai-saketh-cherukuri-825456250" target="_blank">LinkedIn</a> | <a href="https://github.com/ssaketh-ch" target="_blank">GitHub</a>'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
paginate: 3  # Show 3 posts per page
paginate_path: "/page:num/"

pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many paginated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default descending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts)
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages looks like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################

### Phantom settings
admin_name: 'Sai Saketh Cherukuri'
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
  - { url: '/resume', text: 'Resume' }  # Added a "Resume" link in the navigation
